spring:
  jackson:
    time-zone: Asia/Seoul

  config:
    import:
      - security.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    log-request-details: true

  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 80

#  sql.init.mode: always
logging:
  level:
    org:
      springframework:
        web: trace
    org.springframework.web.servlet: trace
    org.hibernate.type.descriptor.sql.BasicBinder: trace

cloud:
  aws:
    credentials:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
    s3:
      bucket: ${AWS_S3_BUCKET}
    region:
      static: ap-northeast-2
    stack:
      auto: false

openai:
  api-key: ${OPEN_AI_KEY}

sagemaker:
  end-point: ${SAGEMAKER_END_POINT}
  api-key: ${SAGEMAKER_API_KEY}

naver:
  client-id: ${NAVER_CLIENT_ID}
  client-secret: ${NAVER_CLIENT_SECRET}