spring:
  jackson:
    time-zone: Asia/Seoul

  config:
    import:
      - security.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SERVER_DB_URL}
    username: ${SERVER_DB_USERNAME}
    password: ${SERVER_DB_PASSWORD}

  data:
    redis:
      host: ${SERVER_REDIS_URL}
      port: ${SERVER_REDIS_PORT}

  mvc:
    throw-exception-if-no-handler-found: true

    path-match:
      matching-strategy: ant_path_matcher
    log-request-details: true

  web:
    resources:
      add-mappings: false

  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 80

cloud:
  aws:
    credentials:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
    s3:
      bucket: ${AWS_S3_BUCKET}
    region:
      static: ap-northeast-2
    stack:
      auto: false

openai:
  api-key: ${OPEN_AI_KEY}

sagemaker:
  end-point: ${SAGEMAKER_END_POINT}
  api-key: ${SAGEMAKER_API_KEY}

naver:
  client-id: ${NAVER_CLIENT_ID}
  client-secret: ${NAVER_CLIENT_SECRET}

springfox:
  documentation:
    enabled: false