spring:
 security:
  oauth2:
    client:
      registration:
        google:
          client-id: ${GOOGLE_CLIENT_ID}
          client-secret: ${GOOGLE_CLIENT_SECRET}
          redirect-uri: "https://api.createver.site/oauth2/authorization/google"
          scope: profile, email

mail:
  address:
    admin: admin@gmail.com

jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 720
  refresh-token-expiration-minutes: 1440

custom:
  oauth:
    redirect:
      host: createver.site
      scheme: https