name: CD

on:
  pull_request:
    branches: [ "main" ]
    types: [ "closed" ]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:

      - name: Runner 환경 Repository 세팅
        uses: actions/checkout@v3

      - name: 아티팩트 다운로드
        uses: actions/download-artifact@v2
        with:
          name: built-artifact
          path: build/libs

      - name: Docker 빌드 & GCR 푸시
        run: |
          echo "${{ secrets.GCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GITH_USERNAME }} --password-stdin
          docker build -t ghcr.io/${{ secrets.GITH_USERNAME }}/createver .
          docker push ghcr.io/${{ secrets.GITH_USERNAME }}/createver

      - name: EC2 배포
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker pull ghcr.io/${{ secrets.GITH_USERNAME }}/createver
            sudo docker rm -f $(sudo docker ps -qa)
            sudo docker run ${{ secrets.DOCKER_RUN_SCRIPT }}
            sudo docker image prune -f

      - name: Discord 알림
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}