name: CI/CD using github actions & docker

# event trigger
on:
  pull_request:
    branches: [ "main" ]
    types: [ "closed" ]

permissions:
  contents: read

jobs:
  CI-CD:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # gradle build
      - name: Build with Gradle
        run: ./gradlew bootJar

      # docker build & gcr push
      - name: Docker build & push
        run: |
          echo "${{ secrets.GCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GITH_USERNAME }} --password-stdin
          docker build -t ghcr.io/${{ secrets.GITH_USERNAME }}/createver .
          docker push ghcr.io/${{ secrets.GITH_USERNAME }}/createver

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker pull ghcr.io/${{ secrets.GITH_USERNAME }}/createver
            sudo docker rm -f $(sudo docker ps -qa)
            sudo docker run ${{ secrets.DOCKER_RUN_SCRIPT }}
            sudo docker image prune -f

      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'