name: CI/CD using github actions & docker

# event trigger
on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # gradle build
      - name: Build with Gradle
        run: ./gradlew bootJar

      # docker build & gcr push
      - name: Docker build & push
        run: |
          echo "${{ secrets.GCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GITH_USERNAME }} --password-stdin
          docker build -t ghcr.io/${{ secrets.GITH_USERNAME }}/createver .
          docker push ghcr.io/${{ secrets.GITH_USERNAME }}/createver
